import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from '@/lib/utils'
import Hero from "@/components/Hero";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Abarrotes Tito - La mejor calidad",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={inter.className}>        
        <main className={cn('relative h-full font-sans antialiased', inter.className)}>
          <Hero />
          <Navbar />
          {children}
        </main>
      </body>
    </html>
  );
}
